services:
  mongo:
    image: mongo:4.4  # Version compatible sans AVX
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/propelize

volumes:
  mongo-data: