name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run backend tests
        run: npm test
        env:
          MONGO_URL: mongodb://localhost:27017/propelize
          JWT_SECRET: your_jwt_secret_key
          JWT_REFRESH_SECRET: your_jwt_refresh_secret_key
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Run MongoDB
        run: docker run -d -p 27017:27017 mongo

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install frontend dependencies
        run: cd frontend && npm install
      - name: Install Playwright browsers
        run: cd frontend && npx playwright install --with-deps
      - name: Run Playwright tests
        run: cd frontend && npm test
      - name: Run linting
        run: cd frontend && npm run lint